# Generated by Django 2.1.4 on 2018-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('PP', 'Paypal'), ('CA', 'Cash')], default='PP', max_length=2)),
            ],
        ),
    ]
