# Generated by Django 2.1.4 on 2018-12-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
