# Generated by Django 2.1.4 on 2018-12-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
