# Generated by Django 2.1.4 on 2019-03-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_attendee_payer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='blah',
            field=models.TextField(default=''),
        ),
    ]
